In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")
sns.set_context("paper", font_scale=2)

%matplotlib inline
plt.style.use('seaborn-ticks')
plt.rcParams.update({'font.size': 14})

In [2]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2],  # стаж
              [500, 700, 750, 600, 1450,        # стоимость занятия
               800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2, 1, 3, 3, 1, 2]], dtype = np.float64) # количество предметов

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype = np.float64) # подходит или нет репетитор

In [3]:
X, y

(array([[1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00,
         1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00],
        [1.00e+00, 1.00e+00, 2.00e+00, 1.00e+00, 3.00e+00, 0.00e+00,
         5.00e+00, 1.00e+01, 1.00e+00, 2.00e+00],
        [5.00e+02, 7.00e+02, 7.50e+02, 6.00e+02, 1.45e+03, 8.00e+02,
         1.50e+03, 2.00e+03, 4.50e+02, 1.00e+03],
        [1.00e+00, 1.00e+00, 2.00e+00, 1.00e+00, 2.00e+00, 1.00e+00,
         3.00e+00, 3.00e+00, 1.00e+00, 2.00e+00]]),
 array([0., 0., 1., 0., 1., 0., 1., 0., 1., 1.]))

#### 2. Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.

In [4]:
def calc_std_feat(x):
    res = (x - x.mean()) / x.std()
    return res

In [5]:
X_st = X.copy()
X_st[2, :] = calc_std_feat(X[2, :])

In [6]:
def calc_logloss(y, y_pred):
    err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
    return err

In [7]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

In [8]:
def eval_model(X, y, iterations, alpha=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T))
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [9]:
W = eval_model(X_st, y, iterations=1000000, alpha=0.01)

100000 [-11.27192801  -1.45338517  -2.38300258   9.49385018] 0.25238285377547093
200000 [-16.2422902   -1.86937288  -3.90462901  13.50867797] 0.2087444482151381
300000 [-20.12046178  -2.20554145  -5.06338174  16.65513544] 0.18225133394128204
400000 [-23.32957684  -2.48701096  -6.00950463  19.2580126 ] 0.16415892687401012
500000 [-26.06999299  -2.72865738  -6.81029352  21.47844134] 0.1509957371068139
600000 [-28.46471856  -2.94024139  -7.50574487  23.41628013] 0.14096415738168322
700000 [-30.59526535  -3.12845003  -8.12178098  25.13788906] 0.13303809324891197
800000 [-32.51817754  -3.29802355  -8.67608723  26.68935959] 0.12659237581823718
900000 [-34.27409432  -3.4524232   -9.18120823  28.10384248] 0.12122604278612226
1000000 [-35.89309329  -3.59424249  -9.64632889  29.40588541] 0.1166708320375139


In [11]:
W = eval_model(X_st, y, iterations=10000, alpha=0.05)

1000 [-1.53736388 -0.9442493   0.98716569  2.45334973] 0.45345340029873327
2000 [-2.77104724 -0.99584438  0.56646496  3.2678674 ] 0.40585173739426816
3000 [-3.76587661 -1.01497984  0.17876379  3.90152678] 0.37490687424857966
4000 [-4.59058643 -1.03598972 -0.13811844  4.4447709 ] 0.35332965359362667
5000 [-5.29406167 -1.06077679 -0.39943091  4.92628384] 0.3373879888006065
6000 [-5.90969753 -1.08772386 -0.62115027  5.36130803] 0.3250090843964675
7000 [-6.46014847 -1.11559407 -0.81446284  5.76016087] 0.3149951165985881
8000 [-6.96100081 -1.14369585 -0.98682915  6.13032491] 0.3066218074591786
9000 [-7.42321206 -1.17167007 -1.14329798  6.47734805] 0.29943145729727527
10000 [-7.85466344 -1.19933686 -1.28738111  6.80540153] 0.2931230243955608


In [10]:
W = eval_model(X_st, y, iterations=10000, alpha=0.001)

1000 [ 0.25805314 -0.68199349  0.68835345  1.24114037] 0.5906912249945011
2000 [ 0.14826604 -0.69312636  0.77941081  1.21302468] 0.5686262548132578
3000 [ 0.06278003 -0.68610936  0.85154153  1.21294398] 0.5559892552843803
4000 [-0.00868429 -0.68420414  0.90686656  1.22453943] 0.5476418419000334
5000 [-0.06998375 -0.68665668  0.94958779  1.24412884] 0.5416473056405607
6000 [-0.12383979 -0.69204716  0.98295258  1.26930679] 0.536958956959128
7000 [-0.17225684 -0.69935379  1.00933215  1.29828381] 0.5330195903831713
8000 [-0.21669501 -0.70786663  1.0304431   1.32974977] 0.5295332269569839
9000 [-0.25821006 -0.71709284  1.04752732  1.36276063] 0.5263411423015845
10000 [-0.29756287 -0.72669083  1.06148576  1.39664388] 0.5233563729128639


Думаю, логично остановиться на 10000 повторениях при альфе = 0,001

#### 3. Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).


In [12]:
def calc_pred_proba(W, x):
    return sigmoid(np.dot(W, x))

In [13]:
y_pred_proba = calc_pred_proba(W, X_st)
y_pred_proba

array([0.27140744, 0.17968469, 0.98119838, 0.2221831 , 0.7103375 ,
       0.35786467, 0.9943532 , 0.10403631, 0.29843831, 0.96412194])

#### 4. Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).

In [14]:
def calc_pred(W, X):    
    m = X.shape[1]
    
    y_predicted = np.zeros((1, m))
    w = W.reshape(X.shape[0], 1)
    
    A = sigmoid(np.dot(w.T, X))
    
#     За порог отнесения к тому или иному классу примем вероятность 0.6(как я поняла, весьма распространенная практика)
    for i in range(A.shape[1]):
        if (A[:,i] > 0.6): 
            y_predicted[:, i] = 1
        elif (A[:,i] <= 0.6):
            y_predicted[:, i] = 0
    
    return y_predicted

In [15]:
y_pred = calc_pred(W, X_st)
y_pred

array([[0., 0., 1., 0., 1., 0., 1., 0., 0., 1.]])